C#/MVC/SistemaWebTransporte/SistemaWebTransporte/Models/Auto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using SistemaWebTransporte.Validaciones;

namespace SistemaWebTransporte.Models
{
    public class Auto
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Modelo { get; set; }
        [Required]
        public string Marca { get; set; }
        [Required]
        [ValidacioAnioAtributo]
        public int Anio { get; set; }
        [Required]
        public string Color { get; set; }
    }
}

C#/MVC/SistemaWebTransporte/SistemaWebTransporte/Controllers/AutoController.cs
using SistemaWebTransporte.Data;
using SistemaWebTransporte.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;

namespace SistemaWebTransporte.Controllers
{
    public class AutoController : Controller
    {
        private SistemaWebTransporteDBContext context = new SistemaWebTransporteDBContext();
        // GET: Auto
        [HttpGet]
        public ActionResult Index()
        {
            List<Auto> lista = context.Autos.ToList();
            return View("Index", lista);
        }
        [HttpGet]
        public ActionResult Create()
        {
            Auto newAuto = new Auto();
            return View("Create", newAuto);
        }
        [HttpPost]
        public ActionResult Create(Auto auto)
        {

            if (ModelState.IsValid)
            {
                context.Autos.Add(auto);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View("Create", auto);
            }
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            Auto auto = context.Autos.Find(id);

            if (auto == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(auto);
            }

        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Auto auto = context.Autos.Find(id);

            if (auto == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View("Delete", auto);
            }

        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Auto auto = context.Autos.Find(id);
            if (auto != null)
            {
                context.Autos.Remove(auto);
                context.SaveChanges();
            }

            return RedirectToAction("Index");

        }






    }
}

C#/MVC/SistemaWebTransporte/SistemaWebTransporte/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaWebTransporte.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.fecha = DateTime.Now.ToString();
            return View();
        }
    }
}

C#/MVC/SistemaWebTransporte/SistemaWebTransporte/Views/Auto/Create.cshtml
@model SistemaWebTransporte.Models.Auto
@{
    ViewBag.Title = "Create";
}

<h1>Nuevo Auto</h1>
@using (Html.BeginForm("Create", "Auto", FormMethod.Post))
{
<p>
    @Html.LabelFor(model => model.Modelo)
    @Html.EditorFor(model => model.Modelo)
    @Html.ValidationMessageFor(model => model.Modelo)
</p>

<p>
    @Html.LabelFor(model => model.Marca)
    @Html.EditorFor(model => model.Marca)
    @Html.ValidationMessageFor(model => model.Marca)
</p>

<p>
    @Html.LabelFor(model => model.Anio)
    @Html.EditorFor(model => model.Anio)
    @Html.ValidationMessageFor(model => model.Anio)
</p>

<p>
    @Html.LabelFor(model => model.Color)
    @Html.EditorFor(model => model.Color)
    @Html.ValidationMessageFor(model => model.Color)
</p>
<input type="submit" value="Create" />

@Html.ActionLink("Go to Index", "Index", "Auto")
}

C#/MVC/SistemaWebTransporte/SistemaWebTransporte/Views/Auto/Delete.cshtml
@model SistemaWebTransporte.Models.Auto


@{
    ViewBag.Title = "Delete";
}



<h3>Desea eliminar este Auto?</h3>

@using (Html.BeginForm("Delete", "Auto", FormMethod.Post))
{
    <div>
        <spam>@Html.DisplayNameFor(model => model.Modelo)</spam>
        <spam>@Html.DisplayFor(model => model.Modelo)</spam>

        <spam>@Html.DisplayNameFor(model => model.Marca)</spam>
        <spam>@Html.DisplayFor(model => model.Marca)</spam>

        <spam>@Html.DisplayNameFor(model => model.Anio)</spam>
        <spam>@Html.DisplayFor(model => model.Anio)</spam>

        <spam>@Html.DisplayNameFor(model => model.Color)</spam>
        <spam>@Html.DisplayFor(model => model.Color)</spam>
    </div>

    <input type="submit" value="Delete" />
}

<p>
    @Html.ActionLink("Go to index", "Index", "Auto")
</p>

C#/MVC/SistemaWebTransporte/SistemaWebTransporte/Views/Auto/Details.cshtml
@model SistemaWebTransporte.Models.Auto
@{
    ViewBag.Title = "Details";
}

<fieldset>
    <legend>Detalle Auto</legend>
    <div>
        @Html.DisplayNameFor(model => model.Modelo)
    </div>
    <div>
        @Html.DisplayFor(model => model.Modelo)
    </div>

    <div>
        @Html.DisplayNameFor(model => model.Marca)
    </div>
    <div>
        @Html.DisplayFor(model => model.Marca)
    </div>

    <div>
        @Html.DisplayNameFor(model => model.Anio)
    </div>
    <div>
        @Html.DisplayFor(model => model.Anio)
    </div>
    <div>
        @Html.DisplayNameFor(model => model.Color)
    </div>
    <div>
        @Html.DisplayFor(model => model.Color)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Go to index", "Index", "Auto")
</p>

C#/MVC/SistemaWebTransporte/SistemaWebTransporte/Views/Auto/Index.cshtml
@model IEnumerable<SistemaWebTransporte.Models.Auto>
@{
    ViewBag.Title = "Index";

}

<h2>Index</h2>

@Html.ActionLink("Nuevo", "Create", "Auto")

<table>
    <tr>
        <th>@Html.DisplayNameFor(model => model.Modelo)</th>
        <th>@Html.DisplayNameFor(model => model.Marca)</th>
        <th>@Html.DisplayNameFor(model => model.Anio)</th>
        <th>@Html.DisplayNameFor(model => model.Color)</th>

    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>@Html.DisplayFor(modelItem => item.Modelo)</td>
    <td>@Html.DisplayFor(modelItem => item.Marca)</td>
    <td>@Html.DisplayFor(modelItem => item.Anio)</td>
    <td>@Html.DisplayFor(modelItem => item.Color)</td>
    <td>@Html.ActionLink("Details", "Details", new { id = item.Id })</td>
    <td>@Html.ActionLink("Delete", "Delete", new { id = item.Id }) </td>
</tr>

}


</table>