C#/MVC/WebEscuelaMVC/WebEscuelaMVC/Models/Aula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using WebEscuelaMVC.Validations;

namespace WebEscuelaMVC.Models
{
    public class Aula
    {
        public int Id { get; set; }

        [Required]
        [CheckValidNumber]
        public int Numero { get; set; }

        [Required]
        public string Estado { get; set;}
    }
}

C#/MVC/WebEscuelaMVC/WebEscuelaMVC/Controllers/AulaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebEscuelaMVC.Data;
using WebEscuelaMVC.Models;

namespace WebEscuelaMVC.Controllers
{
    public class AulaController : Controller
    {
        private AulaDBContext context = new AulaDBContext();

        // GET: Aula
        public ActionResult Index()         // Devuelve vista + todas las aulas
        {
            List<Aula> list = context.Aulas.ToList();
            return View("Index", list);
        }

        // GET: Aula/Create
        public ActionResult Create()    // Devuelve 1 vista "Register"
        {
            Aula aula = new Aula();
            return View("Register", aula);
        }

        // POST: Aula/Create
        [HttpPost]
        public ActionResult Create(Aula aula)   // Guarda la nueva aula en la DB
        {
            if (ModelState.IsValid)
            {
                context.Aulas.Add(aula);
                context.SaveChanges();              // Guarda aula en DB
                return RedirectToAction("Index");
            }
            else
            {
                return View("Register", aula);
            }
        }

        // GET: Aula/Details
        public ActionResult Details (int id)        // Devuelve vista "Detalle" + objeto aula
        {
            Aula aula = context.Aulas.Find(id);
            if (aula == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View("Detalle", aula);
            }
        }

        // GET: Aula/Edit/2
        public ActionResult Edit(int id)        // Devuelve Vista Modificar
        {
            /*if (id == null)       // POR SI EL PARAMETRO ES (int? id)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }*/

            Aula aula = context.Aulas.Find(id);
            if (aula == null)
            {
                return HttpNotFound();
            }
            return View("Edit", aula);

        }

        // POST: /Aula/Edit/2
        [HttpPost]
        public ActionResult Edit(Aula aula)     
        {
            if (ModelState.IsValid) 
            {
                context.Entry(aula).State = EntityState.Modified;       
                context.SaveChanges();              // Guarda aula modificada en DB
                return RedirectToAction("Index");
            }
            return View("Modificar", aula);
        }

        //GET: /Aula/Delete/2
        public ActionResult Delete(int id)
        {
            Aula aula = context.Aulas.Find(id);
            if (aula == null)
            {
                return HttpNotFound();
            }
            return View("Delete", aula);
        }
        //POST: /Aula/Delete/2
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Aula aula = context.Aulas.Find(id);
            if (aula != null)
            {
                context.Aulas.Remove(aula);
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        // GET: /Aula/ListarPorEstado
        /* Busca en la base de datos. Retorna la vista “Index” y la lista de aulas. */
        public ActionResult ListarPorEstado(string estado)
        {
            List<Aula> list = (from a in context.Aulas where estado == a.Estado select a).ToList();
            return View("Index", list);
        }

        // GET: /Aula/TraerPorNumero/1
        public ActionResult TraerPorNumero( int numero) 
        {
            dynamic buscaNum = (from a in context.Aulas where numero == a.Numero select a).ToList();
            return View("Details", buscaNum);           // Busca por numero de aula (se asume que podría haber más de uno por no ser lo mismo que el Id)
        }
    }
}

C#/MVC/WebEscuelaMVC/WebEscuelaMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebEscuelaMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

C#/MVC/WebEscuelaMVC/WebEscuelaMVC/Views/Aula/Create.cshtml
<!--GET: Create - Retorna vista "Register"-->
@model WebEscuelaMVC.Models.Aula

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>
</head>
<body>
    <div>
        <h2>New Classroom</h2>
        @using (Html.BeginForm("Create", "Aula", FormMethod.Post, new
        {
            enctype = "multipart/form-data"
        }))
        {
            @Html.ValidationSummary(true)
            <p>
                @Html.LabelFor(model => model.Numero)
                @Html.EditorFor(model => model.Numero)
                @Html.ValidationMessageFor(model => model.Numero)
            </p>

            <p>
                @Html.LabelFor(model => model.Estado)
                @Html.EditorFor(model => model.Estado)
                @Html.ValidationMessageFor(model => model.Estado)
            </p>

            <p>
                <input type="submit" value="Create" />
                @Html.ActionLink("Register", "Create")
            </p>

        }
    </div>
</body>
</html>

C#/MVC/WebEscuelaMVC/WebEscuelaMVC/Views/Aula/Delete.cshtml
@model WebEscuelaMVC.Models.Aula
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h2>ID: @Model.Id</h2>
    <p>Desea eliminar este aula?</p>

    @using(Html.BeginForm("Delete", "Aula", FormMethod.Post))
            {
                <div>
                    <span>@Html.DisplayNameFor(model => model.Numero):</span>
                    <span>@Html.DisplayFor(model => model.Numero)</span>
                </div>

                <div>
                    <span>@Html.DisplayNameFor(model => model.Estado):</span>
                    <span>@Html.DisplayFor(model => model.Estado)</span>
                </div>
                <input type="submit" name="Delete" value="Eliminar" />
             }
            <p>
                @Html.ActionLink("Go to index", "Index", "Aula")
            </p>
</body>
</html>

C#/MVC/WebEscuelaMVC/WebEscuelaMVC/Views/Aula/Detalle.cshtml
@model WebEscuelaMVC.Models.Aula
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <fieldset>
        <legend>Detalle del aula</legend>
        <div>
            @Html.DisplayNameFor(model => model.Id);
        </div>
        <div>
            @Html.DisplayFor(model => model.Id);
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Numero);
        </div>
        <div>
            @Html.DisplayFor(model => model.Numero);
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Estado);
        </div>
        <div>
            @Html.DisplayFor(model => model.Estado);
        </div>
    </fieldset>
    <p>
        @Html.ActionLink("Go to Index", "Index", "Aula")
    </p>
</body>
</html>

C#/MVC/WebEscuelaMVC/WebEscuelaMVC/Views/Aula/Edit.cshtml
@model WebEscuelaMVC.Models.Aula
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar aula</title>
</head>
<body>
    <h2>Editar datos</h2>
    @using (Html.BeginForm("Edit", "Aula", FormMethod.Post))
    {
        <p>
           Aula @Html.DisplayFor(model => model.Id):
        </p>

        <p>
            @Html.LabelFor(model => model.Numero)
            @Html.EditorFor(model => model.Numero)
            @Html.ValidationMessageFor(model => model.Numero)
        </p>
        <p>
            @Html.LabelFor(model => model.Estado)
            @Html.EditorFor(model => model.Estado)
            @Html.ValidationMessageFor(model => model.Estado)
        </p>
        <input type="submit" value="Guardar cambios" />
        @Html.ActionLink("Go to index", "Index")
    }
</body>
</html>

C#/MVC/WebEscuelaMVC/WebEscuelaMVC/Views/Aula/Index.cshtml
@model IEnumerable<WebEscuelaMVC.Models.Aula>

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Aulas</title>
</head>
<body>
    <div>
        <h2>Todas las aulas</h2>
        <p>
            @Html.ActionLink("Agregar aula", "Create", "Aula")
        </p>
            <table>
                <tr>
                    <th>@Html.DisplayNameFor(a => a.Id)</th>
                    <th>@Html.DisplayNameFor(a => a.Numero)</th>
                    <th>@Html.DisplayNameFor(a => a.Estado)</th>
                </tr>
                @foreach (var item in Model)
                {

                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Id)</td>
                        <td>@Html.DisplayFor(modelItem => item.Numero)</td>
                        <td>@Html.DisplayFor(modelItem => item.Estado)</td>
                        <td>@Html.ActionLink("Detalle", "Details", new { id = item.Id })</td>
                        <td>@Html.ActionLink("Editar", "Edit", new { id = item.Id })</td>
                        <td>@Html.ActionLink("Eliminar", "Delete", new { id = item.Id })</td>
                    </tr>
                }
            </table>
    </div>
</body>
</html>

C#/MVC/WebEscuelaMVC/WebEscuelaMVC/Views/Aula/Register.cshtml
@model WebEscuelaMVC.Models.Aula

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>
</head>
<body>
    <div>
        <h2>New Classroom</h2>
        @using (Html.BeginForm("Create", "Aula", FormMethod.Post))
        {
            <p>
                @Html.LabelFor(model => model.Numero)
                @Html.EditorFor(model => model.Numero)
                @Html.ValidationMessageFor(model => model.Numero)
            </p>

            <p>
                @Html.LabelFor(model => model.Estado)
                @Html.EditorFor(model => model.Estado)
                @Html.ValidationMessageFor(model => model.Estado)
            </p>
                <input type="submit" value="Create" />
                @Html.ActionLink("Go to index", "Index")
        }
    </div>
</body>
</html>